# Generated by Django 3.0.8 on 2020-07-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200720_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='seller',
        ),
    ]
